name: Upload video every 2 hours

on:
  schedule:
    - cron: '15 */2 * * *' 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up ffmpeg
        run: |
            sudo apt-get update
            sudo apt-get install -y ffmpeg
            
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script with secrets
        env:
          FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          PERSONAL_CHAT_ID: ${{ secrets.PERSONAL_CHAT_ID }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
        run: python main.py

      - name: Keep repo alive
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          date > timestamp.txt
          git add timestamp.txt
          git commit -m "chore: keep repo alive !!" || echo "No changes to commit"
          git push
